INSERT INTO COURSE (ID, AUTHOR, COURSE_NAME)
VALUES(100001, 'MAN MANOVICH', 'LEARN JAVA');

INSERT INTO COURSE (ID, AUTHOR, COURSE_NAME)
VALUES(100002, 'GREY ANATOMY', 'LEARN MICROSERVICES');

INSERT INTO COURSE (ID, AUTHOR, COURSE_NAME)
VALUES(100003, 'DAN UBBY', 'LEARN JAVASCRIPT');